# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=30)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gshortintro', models.CharField(max_length=100)),
                ('gstock', models.IntegerField()),
                ('gpic', models.ImageField(upload_to='df_goods')),
                ('gunit', models.CharField(max_length=20)),
                ('isDelet', models.BooleanField(default=False)),
                ('gclick', models.IntegerField()),
                ('gintro', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo'),
        ),
    ]
