# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=20)),
                ('uaddress', models.CharField(max_length=50)),
                ('ushouaddress', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=20)),
                ('uphonenum', models.CharField(max_length=11)),
                ('uyoubian', models.CharField(max_length=7)),
            ],
        ),
    ]
