# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphonenum',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ushouaddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uyoubian',
            field=models.CharField(default='', max_length=7),
        ),
    ]
